### PR TITLE
repo and manifest update: AS 0.6.0.2

### PR DESCRIPTION
**Pull request by phdsg**
reviewed

### CODE REVIEW

**Comment by AndrewBelt** [comment]
Could you post `git remote -v` from your local community repo?

**Comment by phdsg** [comment]
```
$ git remote -v
origin  https://github.com/phdsg/community.git (fetch)
origin  https://github.com/phdsg/community.git (push)
upstream        https://github.com/VCVRack/community.git (fetch)
upstream        https://github.com/VCVRack/community.git (push)

```

**Comment by AndrewBelt** [comment]
Try `git pull upstream master`

**Comment by AndrewBelt** [comment]
And what local branch are you on? If not master, `git merge master`

**Comment by phdsg** [comment]
i'm on master

**Comment by AndrewBelt** [comment]
Did pulling upstream master pull a bunch of commits?

**Comment by phdsg** [comment]
only the AS.json which i edited from the webpage and didn't pull back to local.
```
$ git pull upstream master
remote: Counting objects: 4, done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 4 (delta 0), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (4/4), done.
From https://github.com/VCVRack/community
 * branch            master     -> FETCH_HEAD
   bd5147b..37a08ab  master     -> upstream/master
Merge made by the 'recursive' strategy.
 manifests/AS.json | 3 ++-
 1 file changed, 2 insertions(+), 1 deletion(-)
```

**Pull request merged**
