### PR TITLE
Create AS-Drums-n-Filters

### PR DESCRIPTION
**Pull request by AScustomWorks**

### CODE REVIEW

**Comment by AndrewBelt** [comment]
Some nitpicks
- I feel it that "Pack" should be removed from the human-readable name.
- I don't see a manual on the page that the manual points to, so it should be removed until one is added.

**Comment by AndrewBelt** [comment]
- The manufacturer name should be "AS", not "AS-Drums-n-Filters"

**Comment by AndrewBelt** [comment]
- The [Filters] prefix looks weird. Maybe remove it?

**Comment by AndrewBelt** [comment]
Name refers to the plugin name, it's just unusual to suffix it with "Pack" or "Plugin", since well, that's what it is.
Manufacterer is your "brand", which is "AS".
Remove the "manual" property completely. A blank string is invalid

**Comment by AScustomWorks** [comment]
Oh, ok then:
```
{
  "slug": "AS-Drums-n-Filters",
  "name": "AS Drums & Filters",
  "author": "Alfredo Santamaria",
  "license": "proprietary",
  "version": "0.5.0",
  "homepage": "http://www.hakken.com.mx/ascustomworks/",
  "productId": "1083015692331"
}

Question: changing the slug here to AS instead of AS-Drums-n-Filters, doesn't conflict with the compiled plugin slug? Made it like that to avoid mixing the module list with free and paid modules.

**Comment by AScustomWorks** [comment]
Just noticed, it's done the same way on vcv plugins:
```
  "slug": "VCV-Console",
  "name": "Console",

  "slug": "VCV-PulseMatrix",
  "name": "Pulse Matrix",
```
I guess I'm not getting anywhere by myself.

**Comment by AndrewBelt** [comment]
I think you're confusing slugs with manufacturers. Slugs are always unique IDs that are usually never seen by humans. Manufacturer names help categorize in the Add Module window. The plugin's "name" in the manifests sets the first column of https://vcvrack.com/plugins.html. Ideally, the second column, the "author" should equal the "manufacturer".

I need to get Autodafe to set all of his manufacturer strings to "Autodafe". Blamsoft and VCV are the recommended way.

**Comment by AndrewBelt** [comment]
I also just noticed that you need a .json extension in this file.

I'll fix your manifest, but you need to fix your plugin build.

**Comment by AScustomWorks** [comment]
Indeed I'm mixing things. I think I get it now, let's see (example for v0.5):
On the makefile:
```
SLUG = AS (should be "AS" always in my case)
```
then on the cpp file:
```
p->slug = "AS"; (same thing, it should be "AS" always in my case)
```
and:
```
p->addModel(createModel<Drums8x8KicksWidget>("AS", ...etc
```
This way every module I make (free or paid) will be listed under "AS" in the Add Module window, and that's the expected behavior, right?

**Comment by AndrewBelt** [comment]
No, you need to use this https://github.com/VCVRack/Template/blob/master/src/Template.cpp#L8-L10

Yes to your `addModel` call.

**Comment by AScustomWorks** [comment]
Neat!, doing the plugin build now.

**Pull request merged**
