### PR TITLE
Initial import of plugins working with Rack v0.6 API.

### PR DESCRIPTION
**Pull request by cschol**
[Reference](https://github.com/VCVRack/community/issues/269)

- This is an initial set of plugins that are confirmed to be working on all supported platforms (Win, Lin, Mac) by the Plugin Repair Team.
- The submodule import was driven by a script parsing the .json files in the original repository.
- Some modules are on development branches that work with the v0.6 API and will be updated as soon as the code hits master (or the *final* branch).

### CODE REVIEW

**Comment by cschol** [comment]
Looks like I added the plugins with their REPO names and not the SLUGS. Redoing this.

**Comment by AndrewBelt** [comment]
Reviewing https://github.com/VCVRack/community/pull/320. This might avoid you the trouble, but I'll use yours as a reference if there are any issues.

**Comment by AndrewBelt** [comment]
Or feel free to open a PR if you think you can make it better than his.

**Comment by cschol** [comment]
#322 is an updated version, which has the correct slug directories and only contains plugins that are checked to work. I found some more that have issues in that process and will update the issue list accordingly.

**Pull request closed without merging**
