### PR TITLE
correct name to uppercase to avoid travis complains

### PR DESCRIPTION
**Pull request by antoniotuzzi**
corrected name form nysthi to NYSTHI  to avoid travis complains
new release 0.5.11
added module Dual Feedback Echo
https://www.virustotal.com/#/file/815102b214b1a56c963ad3ea94a6b26ff3e707516ddaa0af15a498d4304bd978/detection

### CODE REVIEW

**Comment by AndrewBelt** [comment]
Travis imposes that the ZIP filename = slug + ".zip"? I don't think it should do that @jeremywen

**Comment by jeremywen** [comment]
This is not what it is complaining about.  `Zip should have one dir named NYSTHI`  The dir inside is lowercase.  Do you want me to ignore case when checking the dir inside the zip?

**Comment by AndrewBelt** [comment]
@jeremywen Ah, okay, that's what I thought. No, it's fine the way it is.

@antoniotuzzi Did we decide earlier to fix the folder problem by making NYSTHI capital? If not, it might be good to change it and make the users deal with the pain for the next release, instead of dealing with later.

**Comment by antoniotuzzi** [comment]
starting from this version, I'll do the UPPERCASE dir!
don't worry!
@jeremywen @AndrewBelt

**Pull request merged**
