### PR TITLE
Create StellareModular.json

### PR DESCRIPTION
**Pull request by sanderbaan**
Initial json file for Stellare Modular plugins

### CODE REVIEW

**Comment by AndrewBelt** [comment]
The version is not compatible with https://github.com/VCVRack/Rack/issues/266

**Comment by sanderbaan** [comment]
Ah its the version number of VCV rack so that would be 0.5.0? We add the link to binaries in a bit and update the SHA

**Comment by AndrewBelt** [comment]
The first part of the version number `v0.5` is the compatibility version, and the second `0.x` is your plugin's revision under that compatibility.

**Comment by sanderbaan** [comment]
So I updated all the fields with a download link and correct sha checksum plus the version number is correct now. Can someone merge this?

**Pull request merged**
