### PR TITLE
Update Valley.json

### PR DESCRIPTION
**Pull request by ValleyAudio**

### CODE REVIEW

**Comment by phdsg** [comment]
i already included `"repoVersion" = "0.6.1"` in my PR.
if i understood correctly, only build team is supposed to change the `latestVersion`

**Comment by ValleyAudio** [comment]
Well to be fair the instructions are bit unclear on that. What is the actual build process now for updating plugins? I've followed the instructions but my plugin manager release is out of date.

**Comment by phdsg** [comment]
the flow goes something like this:
- dev requests update via issue tracker.
- then comes #352 (libraryteam) updating the manifest followed by
- https://github.com/VCVRack/community/issues/354 (reviewteam) checking source code changes and updating the submodule/repo and repoVersion in the json. 
- https://github.com/VCVRack/community/issues/353 (buildteam) picks up there.

**Comment by ValleyAudio** [comment]
Okay, that makes sense. What's the expected turn around time from update to build? I appreciate that this is the Easter weekend for some including myself so I understand if delays are expected.

**Comment by phdsg** [comment]
building and distribution is entirely in andrew's hands (but will be automated in the future).
so, for library and review tasks i guess it depends on how many people get involved and who's online at a given time.

**Comment by ValleyAudio** [comment]
Well to be fair the instructions are little unclear and scattered. I was under the impression that yeah the build team manages this, however

**Comment by ValleyAudio** [comment]
Sorry ignore that last comment, fat buttoned my phone

**Comment by AndrewBelt** [comment]
All plugin developers need to do is https://github.com/VCVRack/community#for-plugin-developers-addingupdating-your-plugin, and we'll handle it from there, usually within a day, but currently within a week while everyone learns the workflow and I get my build system set up. The goal for now is to update `repoVersion` and the submodule's commit hash, which has already been done for your plugin.

**Pull request closed without merging**
