### PR TITLE
manifests for Aepelzens Modules and Parasites

### PR DESCRIPTION
**Pull request by gbrandt1**

### CODE REVIEW

**Comment by AndrewBelt** [comment]
Version is required, slugs are wrong, remove empty string properties, and remove the "downloads" property entirely.

**Comment by gbrandt1** [comment]
which version to assign without tag? 
slugs were first taken from source, then from the manifest filename following error message in the first failure - what are the correct slugs?

**Comment by AndrewBelt** [comment]
Is there no version defined in the repo? The version compiled into the binary takes priority. If there is none, just use 0.5.0.

**Comment by gbrandt1** [comment]
no version, and the slug in the source code has spaces ("Aepelzens Modules") this gave me errors on the first attempt - would like to avoid a fork

**Comment by Phal-anx** [comment]
SLUG and VERSION is missing in the makefile of Apelzens Modules and Apelzens Parasites

**Comment by AndrewBelt** [comment]
I guess if there are any binaries of this plugin going around, the versions compiled with must be completely arbitrary.

**Comment by Phal-anx** [comment]
Definitely! I think the only way would be to fork and fix it

**Comment by AndrewBelt** [comment]
Just checked that nonexistent versions is okay with the server software, so go ahead and make the changes in https://github.com/VCVRack/community/pull/244#issuecomment-363550506 and remove the version property.

**Comment by gbrandt1** [comment]
i don't see how i can remove the spaces without a fork. they're in the .cpp

**Comment by AndrewBelt** [comment]
In the manifest I mean

**Comment by gbrandt1** [comment]
nope :-/
i'll need this fork for committing Southpole... should i remove Aepelzen?

**Comment by gbrandt1** [comment]
i don't understand the errors at this point

**Pull request merged**
