### PR TITLE
repo change: KoralFX

### PR DESCRIPTION
**Pull request by phdsg**

### CODE REVIEW

**Comment by AndrewBelt** [comment]
Maybe something like `git fetch upstream`,  `git merge upstream/master` `git push master origin` would fix your repo?

**Comment by phdsg** [comment]
i always do. except i just `git push` which defaults to `git push origin master` right!?

**Comment by AndrewBelt** [comment]
Yeah, it should. Will probably look at this myself later.

**Comment by phdsg** [comment]
i'll take a brief git lesson on merge strategies

**Comment by cschol** [comment]
Do you create a branch for submitting PRs? I found it cleaner to always create a branch when sending a PR. After the PR is merged then update your `master` from `upstream/master` and delete the branch.

**Comment by phdsg** [comment]
not until now, but i can do that.

**Pull request merged**
