### PR TITLE
Update mental.json

### PR DESCRIPTION
**Pull request by Strum**
added download link for windows release

### CODE REVIEW

**Comment by Strum** [comment]
do i need the sha256 hash?

**Comment by AndrewBelt** [comment]
You don't need it, but it's too useful to pass up. I'd recommend.
You don't have a comma after one of the lines, could you fix that?

**Comment by Strum** [comment]
thanks again Andrew.

you're awesome.

Listened to the interview you did BTW, very cool. I love your approach to programming.

**Comment by AndrewBelt** [comment]
:+1: Thanks!

**Pull request merged**
