### PR TITLE
Update Valley Free.json

### PR DESCRIPTION
**Pull request by ValleyAudio**

### CODE REVIEW

**Comment by AndrewBelt** [comment]
The fact that your slug has a space is a bit problematic. The most important thing is that old patches don't break, but also that it works with the package manager in the future.
I think it should be left this way, and the filename of the ZIP doesn't really matter.

**Comment by ValleyAudio** [comment]
Yeah I've noticed that, I swear it was ValleyRackFree but my memory must be cloudy.

 I would like to ditch the whole "Free" part as I originally intended to make some premium stuff but decided to be completely free. Therefore I want to just become "Valley". 

I noticed Vult did a similar thing and showed people how to fix their patches to work with their new business model, do you think I'd be able to also do this without causing too much pain?

**Comment by AndrewBelt** [comment]
What's the slug in most people's patches? "Valley Free"?

**Comment by ValleyAudio** [comment]
Yeah

**Comment by AndrewBelt** [comment]
If you make premium plugins, put those in another plugin. The Vult developer decided to no longer support the free version and make updates in a commercial plugin only, so he changed the old free plugin from Vult to VultFree or something, and then branched Vult into a commercial plugin.

**Comment by ValleyAudio** [comment]
I'm kinda after doing something similar but instead I'm going completely free and become just "Valley". Yeah I remember Vult told people to edit their vcv save files and change the slugs, which is a PITA but it worked.

I think a safer option for me would be to create just "Valley" and deprecate "Valley Free" after a grace period to give people a chance to catch up. How does that sound to you?

**Comment by AndrewBelt** [comment]
That sounds best if you have the time for it, and if you plan on adding significantly more to the new plugin.

**Pull request merged**
