### PR TITLE
Update FrozenWasteland.json

### PR DESCRIPTION
**Pull request by almostEric**
fixed windows download

### CODE REVIEW

**Comment by AndrewBelt** [comment]
Still no, the root folder doesn't match the slug.

Mind answering my Facebook question?

>Can you explain exactly what you're doing to create the Windows build? The `make dist` should create a proper zip file instead of a tarbomb.

The reason I need to know is because when the Plugin Manager re-opens for free third-party plugins, it would taxi us too much to have this issue come up all the time.

**Comment by AndrewBelt** [comment]
Ah, okay. I have three data points now, so I think I'll make a decision on the future of the Plugin Manager.

**Comment by almostEric** [comment]
I had a friend do the linux and mac builds, which is why those actually worked :)

**Comment by AndrewBelt** [comment]
Even better info!

**Pull request merged**
