### PR TITLE
MrLumps 0.5.0 Update

### PR DESCRIPTION
**Pull request by djpeterso23662**
MrLumps 0.5.0 Update.

### CODE REVIEW

**Comment by AndrewBelt** [comment]
Need a comma on line 12

**Comment by Miserlou** [comment]
So, this is version `0` of your plugin?

**Comment by jeremywen** [comment]
Versioning info here https://github.com/VCVRack/Rack/issues/266

**Comment by AndrewBelt** [comment]
@Miserlou Don't think about it like that. Think: "v0.5.0 is the first build of the plugin for Rack v0.5"

**Comment by djpeterso23662** [comment]
Okay, I think that fixed the comma on line 12 issue.  Thanks!

**Pull request merged**
