### PR TITLE
Create alto777_LFSR

### PR DESCRIPTION
**Pull request by alto777**
I propose to dare to share my plugin. I'm still not sure I'm where I should be doing.

### CODE REVIEW

**Comment by alto777** [comment]
Sorry, this doesn't look like it is headed where I thought, community?

**Comment by cschol** [comment]
Thanks for submitting your plugin. Since this plugin is built against v0.6 of the Rack API, this manifest is not in the correct for for inclusion in the current version of the community repository.

I have added your plugin to the list in the [Repair Thread](https://github.com/VCVRack/community/issues/269), which tracks migration to the new version of the community repository for version 0.6 of Rack.

There are a few issues with the plugin itself. There are logged [here](https://github.com/alto777/LFSR/issues/1).

Once you have fixed those issues, I will add the plugin to the `v2` branch of the community repo. I am tracking the issue above for closure to there is no need to file another PR for the integration.

Looking forward to trying out your plugin.

**Comment by AndrewBelt** [comment]
Also you need a .json extension.

But let's not worry about it, because starting now, we should only accept issues to be handled by the Repair team #269

**Comment by alto777** [comment]
Okay - I intended to build against 0.5.0, since I git cloned Rack and also (I think) "checkout"ed v0.5.

I also thought several odd problems were also fixed by "checkout", in particular two different Template examples.

I'll have a look after breakfast (!) - is there a way to determine which version of Rack I built? I also have regular Rack just from what was my first naive download of the app, it neither seems to divulge its version, nor does OS X "Get Info".

THX.

Oh, while you're here, I see that my LICENSE.txt refers to Andrew Belt, should I just change that to my name? Or add/say something like portions (C) Andrew Bolt (or more accurately tweaks (C) Robert A Moeser)? I have no claims of my own, just want to do the right thing here.

**Comment by AndrewBelt** [comment]
>is there a way to determine which version of Rack I built?

Check the branch you're on with `git branch`. If `master`, then you've built "Rack master", which is the unversioned latest bleeding edge code.
You can also open Rack and look at the title bar for the version.


Your plugin code is your own. If you derived it from the Template plugin, I released that code into the public domain, and I personally believe that using the API of a program is uncopyrightable.

**Comment by alto777** [comment]
OK on license, thanks.

My built Rack is v0.5. I thought doing that would avoid the speeding train problem - easier to work with a non-changing entity.

When I cloned the Template, it failed, natch. That's when I learned about checkout v0.5, which made the first (and all) errors disappear. I got a bad reference to clampf, or something like that and had recalled seeing that it changed from version to version, so…

That means I think that I have been building to v0.5 my plugins. I imagine the thing to do would be to set up a separate Rack dev directory and clone the master? Then see what I need to fix, although so far my plugins do seem to function with the downloaded app.

**Pull request closed without merging**
