### PR TITLE
adds DrumKit, updates SynthKit

### PR DESCRIPTION
**Pull request by JerrySievert**
enjoy!

### CODE REVIEW

**Comment by JerrySievert** [comment]
please retry ci - I hadn't hit release on DrumKit, I was too "fast" on a very slow internet connection.

**Comment by JerrySievert** [comment]
can you help decipher this error message?

I've verified all of the paths, and when attempting to run the specs locally, this is what I receive:

```
 ~/w/R/p/community   master  npm test

> community@1.0.0 test /Users/jerry/work/Rack/plugins/community
> jasmine

No manifest files to test.
Started


No specs found
Finished in 0.003 seconds
```

**Comment by JerrySievert** [comment]
please note that even when I *can* get the tests to run, I still end up with weird errors:

```
bash-3.2$ TEST_MANIFEST=plugins/DrumKit.json npm test

> community@1.0.0 test /Users/jerry/work/Rack/plugins/community
> jasmine

Started
F

Failures:
1) test manifests valid properties and zip files
  Message:
    Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
  Stack:
    Error: Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
        at ontimeout (timers.js:365:14)
        at tryOnTimeout (timers.js:237:5)
        at Timer.listOnTimeout (timers.js:207:5)

1 spec, 1 failure
Finished in 5.058 seconds

npm ERR! Test failed.  See above for more details.
```

seriously, any help with this would be awesome, I'd love to get drumkit and the updated on the community list.

also, re: your comment to my facebook post about pictures, I had tried to, but facebook suspended my account (which I had only created to join the vcvrack community) for "security reasons" after my first and only post, so sadly I was not able to provide pictures :(

**Comment by alikins** [comment]
@JerrySievert My guess would be it the test script doesn't handle two plugins/*.json files being modified in the same pr. The test code looks like it was written to handle multiple files but there doesn't appear to be any previous PRs that do that. So I wouldn't be surprised if that didn't work.

Maybe split it into two PR's? one for each json files?

But  I don't know anything about jasmine or that test setup so take that with a grain of salt.

**Comment by JerrySievert** [comment]
thanks @alikins - I'll go ahead and close this PR and remake 2 new ones.  not going to spend the time to jump into Jasmine (I'm an ex vows maintainer, and tend to use tape/tap when working in node, and equinox when working in plv8).

**Pull request closed without merging**
