### PR TITLE
Create Mental.json

### PR DESCRIPTION
**Pull request by Strum**
Sorry it's taken so long.

### CODE REVIEW

**Comment by AndrewBelt** [comment]
You need to package these with `make dep` with a Makefile that looks like https://github.com/VCVRack/Template/blob/v0.5/Makefile. The ZIPs need to contain a folder with the name of the slug, etc.

**Comment by Strum** [comment]
"You need to package these with make dep with a Makefile that looks like https://github.com/VCVRack/Template/blob/v0.5/Makefile."

Sorry I don't really know what that means or how to do it.

make dep for the module package? or for the app.

"The ZIPs need to contain a folder with the name of the slug, etc."

You are referring to the release zips? yes , I was going to fix them once i worked this json file out, i can take the links out till i get the zips fixed.

**Comment by AndrewBelt** [comment]
Your Makefile looks like https://github.com/Strum/Strums_Mental_VCV_Modules/blob/master/Makefile. It needs to be updated a bit to include the SLUG and VERSION variables, and remove the `dist` target from your own Makefile because it is now supplied by Rack's plugin.mk.

To package your plugin, run `make dist` in your plugin's directory. It appears you are only running `make` and then assembling a ZIP file by picking out the files you wish to include.

**Comment by Strum** [comment]
Ah ha, yes i have just been manually putting the zips together, it worked ok before 5.1

makefiles are still a mystery to me but i should be able to figure it out.

thanks.

**Comment by Strum** [comment]
OK so i changed the makefile and it seemed to work ok, built a distribution for windows and uploaded it.

I've been getting others to do the builds for the other platforms so that might take a day or 2 

i can't seem to edit the json file to add the link.

what do i do now?

thanks for  your time again.

**Comment by AndrewBelt** [comment]
I changed the filename, because the slug is `mental` and is case-sensitive.

**Comment by Strum** [comment]
i thought I had used capital M in the json and makefile should it be all lower case?

**Comment by AndrewBelt** [comment]
https://github.com/Strum/Strums_Mental_VCV_Modules/blob/master/src/mental.cpp#L9 It should be lowercase everywhere.

**Comment by Strum** [comment]
ok, will make another build then, change makefile.

will i be able to edit the json file after it's merged to add the download links and a donation link when i get that sorted?

**Comment by Strum** [comment]
I'll make it M, but i'll sort it out in the code and then change the json.

**Comment by AndrewBelt** [comment]
Sure, just open another PR when you're ready.

The slug cannot change from `mental`, since changing it for perfectionist sake is a poor reason to break everyone's patches.

**Comment by Strum** [comment]
hmmm hadn't thought of that.

oh well should have thought about it a bit more before i started i guess.

stuck with it now.

it's so important to get code right the first time.

**Pull request merged**
