### PR TITLE
Create BaconPlugs.json

### PR DESCRIPTION
**Pull request by baconpaul**
Hi! I've set up my set of plugins, and would like to make them available for the community.  Thanks for making the directions clear. Let me know if there's any problem or what not. Appreciate you all maintaining this community list!

### CODE REVIEW

**Comment by AndrewBelt** [comment]
Looks nice. Before committing, I'll give you the chance to make sure BaconPlugs is the name you want for the slug, since you can't change it after accepting and it's one "plugin" with multiple "modules".

**Comment by baconpaul** [comment]
Hi @AndrewBelt - not sure I understand your comment exactly. I have 5 modules inside the collection each with a name. I thought slug was sort of like the "top level folder" and when I run it in Rack I see that name along side Fundamental and core and stuff; then when I click I see the plugin names (which are also pretty dumb. I'm bad with names!) Should I use slug differently?

Thanks very much!

**Comment by baconpaul** [comment]
Oh or do you mean I should use "Bacon Modules" or some such? If that's what you mean, then cool but I need to do a quick rebuild (which I'm happy to do - we can just dump this PR and I can get it together later on; I'm in no rush!)

**Comment by AndrewBelt** [comment]
I was commenting on the name of your plugin (and therefore its slug). It might make more sense to call it "BaconPlug" instead of "BaconPlugs", or even just "Bacon" since it will be listed along with other plugins which aren't postfixed with "Plugin" or "Plug".

**Comment by baconpaul** [comment]
Ahh gotcha. Well there are 5 modules inside the zip file. So I guess I need a name sort of on par with "Fundamental" or what not.  How about "Bacon Music" as the slug name (and the general description of the suite of things) and then you get the 5 modules under that slug.

Or am I mis-understanding the arity?

Thanks!

**Comment by AndrewBelt** [comment]
You can do whatever you want, but "Bacon Music" definitely makes more sense.

**Comment by baconpaul** [comment]
OK cool. I'm happy to whatever I want, but I'm happier to have whatever I want be something that makes sense. So let me do a rename and rebuild and resubmit with the name Bacon Music. I'll close this PR and have another one in the next few days.

And I appreciate your attention to detail here. This stuff matters. Thanks for the suggestion!

**Pull request closed without merging**
