### PR TITLE
Update 0.5.15 bidoo.json add mac version

### PR DESCRIPTION
**Pull request by sebastien-bouffier**

### CODE REVIEW

**Comment by Phal-anx** [comment]
you need to get rid of the  __MACOSX folder inside the zip file

error message from travis:
Failed: Zip entries should all be under a dir named Bidoo but this entry was found: __MACOSX/

**Comment by sebastien-bouffier** [comment]
Yes I saw it … just passed the archive on VirusTotal and didn’t think that the dist shouldn’t be ok.

I fix it asap.

**Comment by Stratocastix** [comment]
dTrOY is absolutly great !
I noticed that two parameters are not saved in a patch or when the module is duplicated in a patch : Steps and Gate…
Thanks ;-)

**Comment by sebastien-bouffier** [comment]
Thanks. I open an issue [here ](https://github.com/sebastien-bouffier/Bidoo/issues/30) in my repository and check this issue asap. Best.

**Pull request closed without merging**
