### PR TITLE
correct branches for Ohmer, PvC in gitmodules

### PR DESCRIPTION
**Pull request by phdsg**

### CODE REVIEW

**Comment by AndrewBelt** [comment]
Reviewed?

**Comment by phdsg** [comment]
for the FrozenWasteland update: yes... i went over the last commits.
the diff thing you mentioned would be really helpful there.

the others i just added to try the workflow/method.
i think ohmer just switched branches and .gitmodules pointed to one that didn't exist anymore.
with the KoralfxVCV i wanted to try adding a new plugin. gonna have a look over the code later.

**Comment by AndrewBelt** [comment]
Merged. Why does this PR say you've added so many commits? Is your local repo out of sync of the community repo?

**Comment by phdsg** [comment]
most of the commits were done via the github website.
don't know why the already merged ones still show up.
my fork says i'm 39 commits ahead... comparing shows no difference though.

**Comment by phdsg** [comment]
the syncing is still a bit unclear to me.
after i fetch and merge upstream commits, it still says i'm ahead by xx commits but no changed files...

**Pull request merged**
