### PR TITLE
adding Southpole Modular manifest

### PR DESCRIPTION
**Pull request by gbrandt1**

### CODE REVIEW

**Comment by Phal-anx** [comment]
Failed: Zip entries should all be under a dir named Southpole but this entry was found: Southpole-parasites/

**Comment by AndrewBelt** [comment]
You *need* to use `make dist` to build your packages. If you try to ZIP the packages yourself, you will have a bad time committing to this repository.

**Comment by gbrandt1** [comment]
ok. i thought it's cleaner this way. i'll make a second manifest for Southpole-parasites

**Comment by AndrewBelt** [comment]
This is 50% of the reason that I disabled the Plugin Manager for open-source plugins.
Thank you.

**Comment by AndrewBelt** [comment]
But isn't the slug Southpole?

Oh, I see, that repository actually holds two plugins: Southpole and Southpole-parasites. Yes, we need one manifest for each plugin.

**Comment by gbrandt1** [comment]
there is a single module that has to be compiled against parasites. i was hoping to avoid having an extra slug, manifest, files  etc. just for that but i'll add it now

**Comment by AndrewBelt** [comment]
Why not compile that module into the normal Southpole plugin?

**Comment by gbrandt1** [comment]
i was getting name conflicts between the eurorack and the parasites firmware sources. but maybe its easier to resolve those... checking again

**Comment by AndrewBelt** [comment]
For the users, it would be easier if you modified the Parasites source to wrap it in a namespace or something to get around the linking conflicts. Might be worth doing, otherwise two separate plugins would be required.

**Comment by gbrandt1** [comment]
did you have the same conversation with Arabale / Parable Instruments? it was never resolved in that case, was there a technical reason?

**Comment by gbrandt1** [comment]
honestly i would like to avoid too much modifications to parasites since the project of integrating these into Rack seems to have been picked up by other people already. it could be worth if those efforts were abandoned however.

**Comment by AndrewBelt** [comment]
No, that developer just decided that splitting the plugins was best. (see my edit to my last comment)

**Comment by gbrandt1** [comment]
ok i decided to remove the parasites for this round. should be fine now.

**Comment by gbrandt1** [comment]
thx!

**Pull request merged**
